version: "3.0"
services:
 app:
    build:
      context: ./app
      dockerfile: ./dockerfile      
    container_name: flaskPython
    volumes: 
      - ./app:/app
    ports:
      - "5000:5000"

 
volumes:
 app:
