FROM ubuntu:latest

# The EXPOSE instruction indicates the ports on which a container # # will listen for connections
# Since Flask apps listen to port 5000  by default, we expose it
EXPOSE 5000

# Sets the working directory for following COPY and CMD instructions
# Notice we haven’t created a directory by this name - this
# instruction creates a directory with this name if it doesn’t exist
WORKDIR /app

# Install any needed packages specified
RUN apt-get clean && \
        apt-get update && \
        apt-get install -y \
        python3-dev \
        build-essential \
        python3-pip

COPY requirements.txt /app

RUN pip3 install -r requirements.txt

# Run app.py when the container launches

COPY app.py /app

CMD python3 app.py
